[build]
command = "npm install && cd client && npm install && cd ../server && npm install && python -m pip install -r requirements.txt"

[deploy]
command = "bash start.sh"

[env]
PORT = "5000"
NODE_ENV = "production"
FLASK_ENV = "production"

[project]
name = "pulseq"
