services:
  - type: web
    name: pulseq-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://smartqueue:hMN5zLUlWH2JxBRR@smartqueue.unjf9yz.mongodb.net/?retryWrites=true&w=majority&appName=smartqueue
      - key: SECRET_KEY
        value: your-secret-key-here
    healthCheckPath: /health
    startCommand: bash start.sh
    
  - type: static
    name: pulseq-frontend
    buildCommand: cd client && npm install
    staticPublishPath: client
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://pulseq-backend.onrender.com
